### PR TITLE
Docker Tweaks and Fixes to Failing Tests

### PR DESCRIPTION
**Pull request by braidn**
## Pull Request Context

Originally when pulling this repository, there was a single red test. Not sure if this is intended for future candidates or not. However, this PR cleans this up and gives them a full green test suite.

Also included are a few Docker Volume tweaks to somewhat improve IO performance from the host and the container. Most of the information for these volume changes originate from the following article.

https://medium.com/homullus/beating-some-performance-into-docker-for-mac-f5d1e732032c

### CODE REVIEW

**Comment by braidn** [comment]
@bnguyenmindr had a blast today and thought that perhaps some of these changes could be pushed? Not sure but, thank you again for the time.

**Comment by bnguyenmindr** [comment]
Thanks for sending through the PR @braidn! I didn't know about delegated and cached volumes, that's super useful.

Just so you know, the tests are failing on purpose to see if any candidates notice :)

**Comment by braidn** [comment]
> Just so you know, the tests are failing on purpose to see if any candidates notice :)

Hah! I figured.

**Comment by bnguyenmindr** [comment]
Thanks!

**Pull request merged**
